name: Create Q3_archive_java.txt

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Q3_archive_java.txt
      run: |
        echo "Nom et prénom : Hay Baptiste" > Q3_archive_java.txt
        echo "" >> Q3_archive_java.txt
        echo "Contenu du fichier Q3.java :" >> Q3_archive_java.txt
        cat Q3.java >> Q3_archive_java.txt

    - name: Commit and push changes
      run: |
        git config user.name "Biyiv"
        git config user.email "baptiste.hay@hotmail.fr"
        git add Q3_archive_java.txt
        git commit -m "Create Q3_archive_java.txt with Q3.java content"
        git push
